### ISSUE TITLE
Add a newsletter section

### ISSUE THREAD

**Issue by saimaheshtaduri** [muhammad-ahmed02/GUI#1]
Nowadays, newsletters are a common section in every website. I would like to make a newsletter reusable news letter section using React.

**Comment by ch3ber** [comment]
Can you please assign this issue to me?

**Comment by muhammad-ahmed02** [comment]
can you guys share some ideas about the newsletter page how are you thinking to create this?

**Comment by saimaheshtaduri** [comment]
Newsletter section generally subscribes the users taking their emails to send regular updates. This has become quite popular these days. 
I feel a working newsletter section fully working and independent can benefit a lot of websites and can be so useful.

**Comment by ch3ber** [comment]
> can you guys share some ideas about the newsletter page how are you thinking to create this?

Something like [this](https://cdn.dribbble.com/users/2919663/screenshots/17726560/media/69626c5b5dcc9360ca250fa460f365ad.png?compress=1&resize=768x576&vertical=top) removing the menu, replacing the illustrations with others and adjusting the styles to the ones they are currently using.

**Comment by muhammad-ahmed02** [comment]
@ch3ber can you work on the home page and let @saimaheshtaduri work on the newsletter?

**Comment by saimaheshtaduri** [comment]
Sounds good to me. Assign the issue to me. @muhammad-ahmed02

**Comment by ch3ber** [comment]
No problem @muhammad-ahmed02

**Comment by ch3ber** [comment]
assign the home page issue to me

**Comment by muhammad-ahmed02** [comment]
@saimaheshtaduri make sure take a pull of updated code when you create a PR

**Comment by saimaheshtaduri** [comment]
Sure. @muhammad-ahmed02

**Comment by muhammad-ahmed02** [comment]
@saimaheshtaduri are you working on this or should I close the issue?
