### ISSUE TITLE
Improvement of login and register page

### ISSUE THREAD

**Issue by AtriSukul1508** [muhammad-ahmed02/GUI#11]

**Comment by AtriSukul1508** [comment]
i would like to work on this issue

**Comment by muhammad-ahmed02** [comment]
sure you can work on it

**Comment by sumit-022** [comment]
I can improve the pages. Please assigb it to me

**Comment by muhammad-ahmed02** [comment]
> I can improve the pages. Please assigb it to me

already assigned it to you, you can start working
