### ISSUE TITLE
Add cards on Home page having information about founders

### ISSUE THREAD

**Issue by Sam130103** [muhammad-ahmed02/GUI#12]
Nowdays many websites have cards having info about founders and CEO's we can add that feature
@muhammad-ahmed02

**Comment by muhammad-ahmed02** [comment]
My core concept for this website is to create reusable components or pages for people to use in their projects and I don't have many founders for this project its just me so I don't think it will a good idea for this project but you create a such template page for others, what do you think?

**Comment by muhammad-ahmed02** [comment]
@Sam130103 are you working on this or should I close the issue?
