### ISSUE TITLE
Making a spinner component

### ISSUE THREAD

**Issue by RitikJha93** [muhammad-ahmed02/GUI#16]
As a web developer we always use a spinner or a loader while fetching the data from the api.So we can create a spinner component so that developers can use it in their project.

**Comment by muhammad-ahmed02** [comment]
spinners are pretty common components, we can use a material UI spinner as well but as a component, it would be a good idea to create it.

**Comment by RitikJha93** [comment]
I have made the component but it's not getting pushed 
This is the error I am getting

remote: Permission to muhammad-ahmed02/GUI.git denied to RitikJha93.
fatal: unable to access 'https://github.com/muhammad-ahmed02/GUI.git/': The requested URL returned error: 403

**Comment by muhammad-ahmed02** [comment]
Please refer to the readme and follow the guideline on how to fork the repo and create a PR

**Comment by RitikJha93** [comment]
Ok I try by looking at it

**Comment by muhammad-ahmed02** [comment]
@RitikJha93 are you working on this or should I close the issue?
