### ISSUE TITLE
Add a contact us section

### ISSUE THREAD

**Issue by saimaheshtaduri** [muhammad-ahmed02/GUI#2]
Implementing a contact us form template for reusability.

**Comment by muhammad-ahmed02** [comment]
yes sure, almost every website should have a contact us page so it will be usefull

**Comment by muhammad-ahmed02** [comment]
@saimaheshtaduri are you working on this or should I close the issue?

**Comment by saimaheshtaduri** [comment]
I am facing issues with project setup actually, that's the reason for delay. Is there any resource I can follow ? @muhammad-ahmed02

**Comment by muhammad-ahmed02** [comment]
> I am facing issues with project setup actually, that's the reason for delay. Is there any resource I can follow ? @muhammad-ahmed02

just delete your nodemodules folders and run `npm i` it will install all the dependencies after it completes run `npm start`
