### ISSUE TITLE
Home page

### ISSUE THREAD

**Issue by ch3ber** [muhammad-ahmed02/GUI#3]
Can I create a home page with links to the demo pages?

**Comment by muhammad-ahmed02** [comment]
Sure that would be interesting but can you make it dynamic so that in the future if anyone creates any other page it should also be listed on the home page or any sidebar would also be a good idea

**Comment by ch3ber** [comment]
I don't think it's possible to do it dynamically, you could try with node.js but I think it's better to do it manually.

**Comment by muhammad-ahmed02** [comment]
Ok then you can work on the design of home page

**Comment by ch3ber** [comment]
Can you add the hacktoberfest tag to this topic and assign this topic to me?
It is for [Hacktoberfest](https://hacktoberfest.com/participation/#maintainers) requirements.

**Comment by ch3ber** [comment]
Just created the PR

**Comment by muhammad-ahmed02** [comment]
PR is merged thank you, closing the issue
