### ISSUE TITLE
Want to improve the footer

### ISSUE THREAD

**Issue by KiranAminPanjwani** [muhammad-ahmed02/GUI#30]
<h3>Describe the bug:</h3>

##### A clear and concise description of what the bug is.

- I want to improve the styling of the footer section
- I'm a HAcktoberfest participant, kindly assign this issue to me.😊

**Screenshots** If applicable, add screenshots to help explain your problem.

![image](https://user-images.githubusercontent.com/90326051/194367540-f1e6742c-83ff-4390-b59c-2770be51ff2f.png)

**Comment by muhammad-ahmed02** [comment]
Sure, you can work on that.
