### ISSUE TITLE
Blog category page

### ISSUE THREAD

**Issue by devfaoed** [muhammad-ahmed02/GUI#32]
Category page for different section of the blog part and footer and navbar for the blog

**Comment by muhammad-ahmed02** [comment]
We already have a footer and navbar, you can work on only the blog page, and you can put actual images instead of size samples it would be more appealing.

**Comment by devfaoed** [comment]
Ok

**Comment by muhammad-ahmed02** [comment]
@devfaoed are you working on this or should I close the issue?

**Comment by devfaoed** [comment]
U can close the issue
