### ISSUE TITLE
Navigation bar and linter

### ISSUE THREAD

**Issue by ch3ber** [muhammad-ahmed02/GUI#6]
- add navigation bar on all pages
- add linter
- add 404 error page

**Comment by muhammad-ahmed02** [comment]
sure you can work on this but make sure you create a layout for the navigation bar so it may dynamically appear on every page

**Comment by ch3ber** [comment]
Thank you I'll make a PR soon

**Comment by muhammad-ahmed02** [comment]
@ch3ber can you leave the 404 error page so I can give it to someone else so they can also create PR?

**Comment by ch3ber** [comment]
Sure but only the 404 error page, because I want contribute to the project:)

**Comment by ch3ber** [comment]
@muhammad-ahmed02  How do you like to write code, with semicolons or without semicolons? in my personal opinion I prefer without semicolons. I usually use [StandardJS](https://standardjs.com/) in all my projects.

**Comment by muhammad-ahmed02** [comment]
I use prettier for this stuff and prettier usually adds semi-colon 😄

**Comment by muhammad-ahmed02** [comment]
ok sure no problem

**Comment by muhammad-ahmed02** [comment]
Thank you for your contribution! closing this issue now
