### ISSUE TITLE
404 Page Component

### ISSUE THREAD

**Issue by dipanshusingh2107** [muhammad-ahmed02/GUI#8]
I would like to create a 404 page.
If you have some Idea please share

**Comment by dipanshusingh2107** [comment]
![404](https://user-images.githubusercontent.com/47363596/193505451-925aa1e1-252c-4bf0-8afb-16586bc87ad1.jpg)
Looking to create something like this

**Comment by muhammad-ahmed02** [comment]
Yes sure it looks great you can start working on it right away
